### ISSUE TITLE
所以你的代码呢？

### ISSUE THREAD

**Issue by Eastforward** [HOCOOH/Auto-fishing-Mole-world#1]
### rt

**Comment by HOCOOH** [comment]
因为涉及到可能的侵权问题，源代码不公开（其实是我建仓库的时候选错了）
我只说一下实现思路：
win32 api获取窗口，截屏
win32 api或pyautogui控制点击，也可以使用模拟器的按键映射
判断鱼上钩：pyautogui图像识别钓鱼的按键（鱼上钩后会出现条纹和星星）
判断鱼在圈内：opencv hsv做颜色筛选，识别圈（蓝色）和鱼（蓝色）
这样放在循环体里就可以
